const STORE='v4_crm_bridge_ui_v1';
const tabs=[
  ['dashboard','Dashboard','i-dashboard','v4'],['accounts','Accounts','i-accounts','blue'],['clients','Clientes','i-clients','orange'],['integrations','Integracoes','i-crm','v4'],['mapping','Mapeamento','i-map','blue'],['sync','Sync','i-sync','v4'],['audit','Auditoria','i-audit','red'],['logs','Logs','i-logs','orange'],['settings','Config','i-settings','blue']
];
const baseFields=['Data','Lead ID','Nome','Valor','LEAD','MQL','SQL','OPORTUNIDADE','COMPRA','LEAD PERDIDO','META ADS','GOOGLE ADS','RESPONSAVEL','MOTIVO DE PERDA'];
function state(){return JSON.parse(localStorage.getItem(STORE)||'{"tab":"dashboard","accounts":[],"clients":[],"integrations":[],"logs":[],"settings":{"operator":"Vinicius Agnes","email":"vinicius.agnes@v4company.com"}}')}
function save(s){localStorage.setItem(STORE,JSON.stringify(s));render()}
function log(type,msg){const s=state();s.logs.unshift({type,msg,at:new Date().toLocaleString('pt-BR')});save(s)}
function icon(cls,color='v4'){return `<span class="icon ${color} ${cls}"></span>`}
function setTab(id){const s=state();s.tab=id;save(s)}
function seed(){const s=state();s.accounts=[{name:'Vinicius Agnes',email:'vinicius.agnes@v4company.com',role:'admin'}];s.clients=[{name:'ST1 Internet',account:'vinicius.agnes@v4company.com',sheet:'GrowthPack ST1',status:'ativo'},{name:'Cliente Demo',account:'vinicius.agnes@v4company.com',sheet:'GrowthPack Demo',status:'implantacao'}];s.integrations=[{client:'ST1 Internet',crm:'kommo',alias:'credencial_st1',status:'ativo'}];s.logs.unshift({type:'success',msg:'Base demo carregada',at:new Date().toLocaleString('pt-BR')});save(s)}
function addAccount(e){e.preventDefault();const s=state();s.accounts.unshift({name:accName.value,email:accEmail.value,role:accRole.value});save(s);e.target.reset();log('success','Account cadastrado')}
function addClient(e){e.preventDefault();const s=state();s.clients.unshift({name:clientName.value,account:clientAccount.value,sheet:growthpack.value,status:clientStatus.value});save(s);e.target.reset();log('success','Cliente cadastrado')}
function addIntegration(e){e.preventDefault();const s=state();s.integrations.unshift({client:intClient.value,crm:intCrm.value,alias:intAlias.value,status:intStatus.value});save(s);e.target.reset();log('success','Integracao cadastrada')}
function syncClient(name){const s=state();const c=s.clients.find(x=>x.name===name);if(c){c.lastSync=new Date().toLocaleString('pt-BR');c.records=Math.floor(Math.random()*120)+10}save(s);log('success','Sync preview executado para '+name)}
function runAudit(){const s=state();const issues=[];s.clients.forEach(c=>{if(!s.integrations.find(i=>i.client===c.name))issues.push([c.name,'Sem integracao CRM','Cadastrar conexao CRM','Alta']);if(!c.sheet)issues.push([c.name,'Sem GrowthPack','Cadastrar planilha destino','Alta'])});s.audit=issues;save(s);log('success','Auditoria executada')}
function removeClient(name){const s=state();s.clients=s.clients.filter(c=>c.name!==name);save(s);log('success','Cliente removido')}
function exportData(){const blob=new Blob([JSON.stringify(state(),null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='v4-crm-bridge.json';a.click()}
function layout(content){const s=state();return `<div class="shell"><aside class="side"><div class="brand"><div class="mark">V4</div><div><h1>CRM Bridge</h1><p>Sistema exclusivo V4</p></div></div><nav class="nav">${tabs.map(t=>`<button class="${s.tab===t[0]?'active':''}" onclick="setTab('${t[0]}')">${icon(t[2],t[3])}<span>${t[1]}</span></button>`).join('')}</nav><div style="margin-top:22px" class="card"><b>${s.settings.operator}</b><p class="muted">${s.settings.email}</p><button class="btn secondary" onclick="seed()">Carregar demonstracao</button></div></aside><main class="main"><header class="top"><div><h2>${tabs.find(t=>t[0]===s.tab)?.[1]||'Dashboard'}</h2><p>CRM, GrowthPack, BASE_CRM e auditoria operacional.</p></div><div class="actions"><button class="btn primary" onclick="setTab('sync')">Sincronizar</button><button class="btn secondary" onclick="exportData()">Exportar</button></div></header>${content}<footer class="muted">V4 CRM Bridge - sem emoji, com icones proprietarios do sistema.</footer></main></div>`}
function dashboard(){const s=state();return `<div class="card"><h1 class="hero">Integracao de CRM para <span>accounts V4</span>.</h1><p class="muted">Sistema responsivo para cadastro, integracoes, mapeamento, sync e auditoria.</p></div><div class="kpis"><div class="kpi"><small>Accounts</small><b>${s.accounts.length}</b></div><div class="kpi"><small>Clientes</small><b>${s.clients.length}</b></div><div class="kpi"><small>Integracoes</small><b>${s.integrations.length}</b></div><div class="kpi"><small>Logs</small><b>${s.logs.length}</b></div></div><div class="grid"><div class="card"><h3>Matriz V4</h3><p class="muted">Automatizar coleta, organizacao, logs e auditoria. Validar decisoes sensiveis.</p></div><div class="card"><h3>Ultimos logs</h3><div class="logs">${s.logs.slice(0,5).map(l=>`<div class="log"><b>${l.type}</b><br>${l.msg}<br>${l.at}</div>`).join('')||'<div class="empty">Sem logs.</div>'}</div></div></div>`}
function accounts(){const s=state();return `<div class="grid"><form class="card" onsubmit="addAccount(event)"><h3>Novo account</h3><label>Nome</label><input id="accName" required><label>Email</label><input id="accEmail" required><label>Perfil</label><select id="accRole"><option>admin</option><option>account</option><option>viewer</option></select><br><br><button class="btn primary">Salvar</button></form><div class="card"><h3>Accounts</h3><div class="list">${s.accounts.map(a=>`<div class="item"><div><h4>${a.name}</h4><p>${a.email}</p><span class="pill">${a.role}</span></div></div>`).join('')||'<div class="empty">Nenhum account.</div>'}</div></div></div>`}
function clients(){const s=state();return `<div class="grid"><form class="card" onsubmit="addClient(event)"><h3>Novo cliente</h3><label>Nome</label><input id="clientName" required><label>Account</label><select id="clientAccount">${s.accounts.map(a=>`<option>${a.email}</option>`).join('')}</select><label>GrowthPack</label><input id="growthpack" required><label>Status</label><select id="clientStatus"><option>ativo</option><option>implantacao</option><option>pausado</option></select><br><br><button class="btn primary">Salvar</button></form><div class="card"><h3>Clientes</h3><div class="list">${s.clients.map(c=>`<div class="item"><div><h4>${c.name}</h4><p>${c.account}</p><span class="pill">${c.status}</span></div><div><button class="btn secondary" onclick="syncClient('${c.name}')">Sync</button><button class="btn secondary" onclick="removeClient('${c.name}')">Remover</button></div></div>`).join('')||'<div class="empty">Nenhum cliente.</div>'}</div></div></div>`}
function integrations(){const s=state();return `<div class="grid"><form class="card" onsubmit="addIntegration(event)"><h3>Nova integracao</h3><label>Cliente</label><select id="intClient">${s.clients.map(c=>`<option>${c.name}</option>`).join('')}</select><label>CRM</label><select id="intCrm"><option>kommo</option><option>rdstation</option><option>hubspot</option><option>moskit</option></select><label>Alias seguro</label><input id="intAlias" required><label>Status</label><select id="intStatus"><option>ativo</option><option>pendente</option><option>erro</option></select><br><br><button class="btn primary">Salvar</button></form><div class="card"><h3>Integracoes</h3>${s.integrations.map(i=>`<div class="item"><div><h4>${i.client}</h4><p>${i.crm} - ${i.alias}</p><span class="pill">${i.status}</span></div></div>`).join('')||'<div class="empty">Nenhuma integracao.</div>'}</div></div>`}
function mapping(){return `<div class="card"><h3>Mapeamento BASE_CRM</h3><div class="table"><table><thead><tr><th>Campo V4</th><th>Origem CRM</th></tr></thead><tbody>${baseFields.map(f=>`<tr><td>${f}</td><td><input value="${f.toLowerCase().replaceAll(' ','_')}"></td></tr>`).join('')}</tbody></table></div></div>`}
function sync(){const s=state();return `<div class="card"><h3>Fila de sincronizacao</h3><div class="table"><table><thead><tr><th>Cliente</th><th>Status</th><th>Ultimo sync</th><th>Registros</th><th>Ação</th></tr></thead><tbody>${s.clients.map(c=>`<tr><td>${c.name}</td><td>${c.status}</td><td>${c.lastSync||'-'}</td><td>${c.records||0}</td><td><button class="btn primary" onclick="syncClient('${c.name}')">Sync</button></td></tr>`).join('')}</tbody></table></div></div>`}
function audit(){const s=state();return `<div class="card"><h3>Auditoria</h3><button class="btn primary" onclick="runAudit()">Rodar auditoria</button></div><div class="card"><div class="table"><table><thead><tr><th>Cliente</th><th>Problema</th><th>Ação</th><th>Severidade</th></tr></thead><tbody>${(s.audit||[]).map(a=>`<tr><td>${a[0]}</td><td>${a[1]}</td><td>${a[2]}</td><td>${a[3]}</td></tr>`).join('')}</tbody></table></div></div>`}
function logs(){const s=state();return `<div class="card"><h3>Logs</h3><div class="logs">${s.logs.map(l=>`<div class="log"><b>${l.type}</b><br>${l.msg}<br>${l.at}</div>`).join('')||'<div class="empty">Sem logs.</div>'}</div></div>`}
function settings(){const s=state();return `<form class="card" onsubmit="event.preventDefault();const st=state();st.settings.operator=operator.value;st.settings.email=email.value;save(st);log('success','Configuracoes atualizadas')"><h3>Configuracoes</h3><label>Operador</label><input id="operator" value="${s.settings.operator}"><label>Email</label><input id="email" value="${s.settings.email}"><br><br><button class="btn primary">Salvar</button></form>`}
function render(){const s=state();const pages={dashboard,accounts,clients,integrations,mapping,sync,audit,logs,settings};document.getElementById('app').innerHTML=layout((pages[s.tab]||dashboard)())}
window.setTab=setTab;window.seed=seed;window.addAccount=addAccount;window.addClient=addClient;window.addIntegration=addIntegration;window.syncClient=syncClient;window.runAudit=runAudit;window.exportData=exportData;window.removeClient=removeClient;render();